# Camera intrinsics
width: 1920 # Horizontal image resolution in pixels
height: 1200 # Vertical image resolution in pixels
fx: 3989.8780043720185 # Horizontal focal-length component in pixels
fy: 3979.5155237090626 # Vertical focal-length component in pixels
cx: 929.2145184159839 # Horizontal coordinate of focal origin in pixels
cy: 573.8104744765726 # Vertical coordinate of focal origin in pixels

# width: 1920 # Horizontal image resolution in pixels
# height: 1200 # Vertical image resolution in pixels
# fx: 4279.799962827053 # Horizontal focal-length component in pixels
# fy: 3718.178701411081 # Vertical focal-length component in pixels
# cx: 795.5825195152659 # Horizontal coordinate of focal origin in pixels
# cy: 545.589603771995 # Vertical coordinate of focal origin in pixels